var group__hal__capi =
[
    [ "PDP Functions", "group__hal__pdp.html", "group__hal__pdp" ],
    [ "REV Power Distribution Hub API Functions", "group__hal__rev__pdh.html", "group__hal__rev__pdh" ],
    [ "Accelerometer Functions", "group__hal__accelerometer.html", "group__hal__accelerometer" ],
    [ "Addressable LED Functions", "group__hal__addressable.html", null ],
    [ "Analog Accumulator Functions", "group__hal__analogaccumulator.html", "group__hal__analogaccumulator" ],
    [ "Analog Gyro Functions", "group__hal__analoggyro.html", "group__hal__analoggyro" ],
    [ "Analog Input Functions", "group__hal__analoginput.html", "group__hal__analoginput" ],
    [ "Analog Output Functions", "group__hal__analogoutput.html", "group__hal__analogoutput" ],
    [ "Analog Trigger Functions", "group__hal__analogtrigger.html", "group__hal__analogtrigger" ],
    [ "CAN Stream Functions", "group__hal__canstream.html", "group__hal__canstream" ],
    [ "CAN API Functions", "group__hal__canapi.html", "group__hal__canapi" ],
    [ "Constants Functions", "group__hal__constants.html", "group__hal__constants" ],
    [ "Counter Functions", "group__hal__counter.html", "group__hal__counter" ],
    [ "CTRE PCM Functions", "group__hal__ctre__pcm.html", null ],
    [ "DIO Functions", "group__hal__dio.html", "group__hal__dio" ],
    [ "DMA Functions", "group__hal__dma.html", "group__hal__dma" ],
    [ "Driver Station Functions", "group__hal__driverstation.html", "group__hal__driverstation" ],
    [ "DutyCycle Functions", "group__hal__dutycycle.html", "group__hal__dutycycle" ],
    [ "Encoder Functions", "group__hal__encoder.html", "group__hal__encoder" ],
    [ "Error Defines", "group__hal__errors.html", null ],
    [ "Simulator Extensions", "group__hal__extensions.html", "group__hal__extensions" ],
    [ "I2C Functions", "group__hal__i2c.html", "group__hal__i2c" ],
    [ "Interrupts Functions", "group__hal__interrupts.html", "group__hal__interrupts" ],
    [ "Main loop functions", "group__hal__relay.html", "group__hal__relay" ],
    [ "Notifier Functions", "group__hal__notifier.html", "group__hal__notifier" ],
    [ "Ports Functions", "group__hal__ports.html", "group__hal__ports" ],
    [ "Power Functions", "group__hal__power.html", "group__hal__power" ],
    [ "Power Distribution Functions", "group__hal__pd.html", "group__hal__pd" ],
    [ "PWM Output Functions", "group__hal__pwm.html", "group__hal__pwm" ],
    [ "REV PH Functions", "group__hal__rev__ph.html", "group__hal__rev__ph" ],
    [ "Serial Port Functions", "group__hal__serialport.html", "group__hal__serialport" ],
    [ "Simulator Device Framework", "group__hal__simdevice.html", "group__hal__simdevice" ],
    [ "SPI Functions", "group__hal__spi.html", "group__hal__spi" ],
    [ "Threads Functions", "group__hal__threads.html", "group__hal__threads" ],
    [ "Type Definitions", "group__hal__types.html", null ],
    [ "HAL_ExpandFPGATime", "group__hal__capi.html#ga7fda7ce97de711c9dfc5bb8bed9a79ed", null ],
    [ "HAL_GetBrownedOut", "group__hal__capi.html#gaa08f0d857909be9eb98cdb71189eca0c", null ],
    [ "HAL_GetErrorMessage", "group__hal__capi.html#ga353fed1ef0582ec7418d21a458042e67", null ],
    [ "HAL_GetFPGAButton", "group__hal__capi.html#ga24551a662a649f5abbab9ac468bfe44f", null ],
    [ "HAL_GetFPGARevision", "group__hal__capi.html#ga92246516e9f543f8b73ffaa1f085d626", null ],
    [ "HAL_GetFPGATime", "group__hal__capi.html#ga90870d91c61183d070b6064020e8a0c8", null ],
    [ "HAL_GetFPGAVersion", "group__hal__capi.html#ga9673988f8c8dcb3c9c0e3b11d5b2550d", null ],
    [ "HAL_GetLastError", "group__hal__capi.html#ga069915df2a6264568b8da8628bb6c276", null ],
    [ "HAL_GetPort", "group__hal__capi.html#ga1a4017232c3d7f86712544dfdd9d5dca", null ],
    [ "HAL_GetPortWithModule", "group__hal__capi.html#gae581c7334cf37b57b6b12d3e9113ab74", null ],
    [ "HAL_GetRuntimeType", "group__hal__capi.html#ga8ffc0f5069623bdac62037716ba23156", null ],
    [ "HAL_GetSystemActive", "group__hal__capi.html#ga5aaf51b826034ad48b05e02e3736b687", null ],
    [ "HAL_Initialize", "group__hal__capi.html#gad72b2804c3cb301e53d90f0e61f2137f", null ],
    [ "HAL_Shutdown", "group__hal__capi.html#gafccf269a24459a444068863528a7c963", null ],
    [ "HAL_SimPeriodicAfter", "group__hal__capi.html#gaf2d1ec0dcf2d988d78606df3f6c9f765", null ],
    [ "HAL_SimPeriodicBefore", "group__hal__capi.html#gaf88a3a55375664d6b8333819edb19d5c", null ]
];