var namespacecs =
[
    [ "impl", null, [
      [ "ListenerData", "structcs_1_1impl_1_1_listener_data.html", "structcs_1_1impl_1_1_listener_data" ],
      [ "NotifierThread", "classcs_1_1impl_1_1_notifier_thread.html", "classcs_1_1impl_1_1_notifier_thread" ]
    ] ],
    [ "AxisCamera", "classcs_1_1_axis_camera.html", "classcs_1_1_axis_camera" ],
    [ "AxisCameraImpl", "classcs_1_1_axis_camera_impl.html", "classcs_1_1_axis_camera_impl" ],
    [ "ComPtr", "classcs_1_1_com_ptr.html", "classcs_1_1_com_ptr" ],
    [ "ConfigurableSourceImpl", "classcs_1_1_configurable_source_impl.html", "classcs_1_1_configurable_source_impl" ],
    [ "CvSinkImpl", "classcs_1_1_cv_sink_impl.html", "classcs_1_1_cv_sink_impl" ],
    [ "CvSourceImpl", "classcs_1_1_cv_source_impl.html", "classcs_1_1_cv_source_impl" ],
    [ "default_init_allocator", "classcs_1_1default__init__allocator.html", "classcs_1_1default__init__allocator" ],
    [ "Frame", "classcs_1_1_frame.html", "classcs_1_1_frame" ],
    [ "Handle", "classcs_1_1_handle.html", "classcs_1_1_handle" ],
    [ "HttpCamera", "classcs_1_1_http_camera.html", "classcs_1_1_http_camera" ],
    [ "HttpCameraImpl", "classcs_1_1_http_camera_impl.html", "classcs_1_1_http_camera_impl" ],
    [ "Image", "classcs_1_1_image.html", "classcs_1_1_image" ],
    [ "ImageSink", "classcs_1_1_image_sink.html", "classcs_1_1_image_sink" ],
    [ "ImageSource", "classcs_1_1_image_source.html", "classcs_1_1_image_source" ],
    [ "Instance", "classcs_1_1_instance.html", "classcs_1_1_instance" ],
    [ "MjpegServer", "classcs_1_1_mjpeg_server.html", "classcs_1_1_mjpeg_server" ],
    [ "MjpegServerImpl", "classcs_1_1_mjpeg_server_impl.html", "classcs_1_1_mjpeg_server_impl" ],
    [ "NetworkListener", "classcs_1_1_network_listener.html", "classcs_1_1_network_listener" ],
    [ "Notifier", "classcs_1_1_notifier.html", "classcs_1_1_notifier" ],
    [ "PropertyContainer", "classcs_1_1_property_container.html", "classcs_1_1_property_container" ],
    [ "PropertyImpl", "classcs_1_1_property_impl.html", "classcs_1_1_property_impl" ],
    [ "RawCvSink", "classcs_1_1_raw_cv_sink.html", "classcs_1_1_raw_cv_sink" ],
    [ "RawCvSource", "classcs_1_1_raw_cv_source.html", "classcs_1_1_raw_cv_source" ],
    [ "RawEvent", "structcs_1_1_raw_event.html", "structcs_1_1_raw_event" ],
    [ "RawSinkImpl", "classcs_1_1_raw_sink_impl.html", "classcs_1_1_raw_sink_impl" ],
    [ "RawSourceImpl", "classcs_1_1_raw_source_impl.html", "classcs_1_1_raw_source_impl" ],
    [ "RemoveAddRefRelease", "classcs_1_1_remove_add_ref_release.html", "classcs_1_1_remove_add_ref_release" ],
    [ "SinkData", "structcs_1_1_sink_data.html", "structcs_1_1_sink_data" ],
    [ "SinkImpl", "classcs_1_1_sink_impl.html", "classcs_1_1_sink_impl" ],
    [ "SourceData", "structcs_1_1_source_data.html", "structcs_1_1_source_data" ],
    [ "SourceImpl", "classcs_1_1_source_impl.html", "classcs_1_1_source_impl" ],
    [ "SourceReaderCB", "classcs_1_1_source_reader_c_b.html", "classcs_1_1_source_reader_c_b" ],
    [ "Telemetry", "classcs_1_1_telemetry.html", "classcs_1_1_telemetry" ],
    [ "UnlimitedHandleResource", "classcs_1_1_unlimited_handle_resource.html", "classcs_1_1_unlimited_handle_resource" ],
    [ "UsbCamera", "classcs_1_1_usb_camera.html", "classcs_1_1_usb_camera" ],
    [ "UsbCameraBuffer", "classcs_1_1_usb_camera_buffer.html", "classcs_1_1_usb_camera_buffer" ],
    [ "UsbCameraImpl", "classcs_1_1_usb_camera_impl.html", "classcs_1_1_usb_camera_impl" ],
    [ "UsbCameraInfo", "structcs_1_1_usb_camera_info.html", "structcs_1_1_usb_camera_info" ],
    [ "UsbCameraListener", "classcs_1_1_usb_camera_listener.html", "classcs_1_1_usb_camera_listener" ],
    [ "UsbCameraProperty", "classcs_1_1_usb_camera_property.html", "classcs_1_1_usb_camera_property" ],
    [ "VideoCamera", "classcs_1_1_video_camera.html", "classcs_1_1_video_camera" ],
    [ "VideoEvent", "classcs_1_1_video_event.html", "classcs_1_1_video_event" ],
    [ "VideoListener", "classcs_1_1_video_listener.html", "classcs_1_1_video_listener" ],
    [ "VideoMode", "structcs_1_1_video_mode.html", "structcs_1_1_video_mode" ],
    [ "VideoProperty", "classcs_1_1_video_property.html", "classcs_1_1_video_property" ],
    [ "VideoSink", "classcs_1_1_video_sink.html", "classcs_1_1_video_sink" ],
    [ "VideoSource", "classcs_1_1_video_source.html", "classcs_1_1_video_source" ],
    [ "WindowsMessagePump", "classcs_1_1_windows_message_pump.html", "classcs_1_1_windows_message_pump" ]
];