var namespacewpi_1_1detail =
[
    [ "AlignerImpl", "classwpi_1_1detail_1_1_aligner_impl.html", "classwpi_1_1detail_1_1_aligner_impl" ],
    [ "ConstantLog2", "structwpi_1_1detail_1_1_constant_log2.html", null ],
    [ "ConstantLog2< 1 >", "structwpi_1_1detail_1_1_constant_log2_3_011_01_4.html", null ],
    [ "DenseMapPair", "structwpi_1_1detail_1_1_dense_map_pair.html", "structwpi_1_1detail_1_1_dense_map_pair" ],
    [ "exception", "classwpi_1_1detail_1_1exception.html", "classwpi_1_1detail_1_1exception" ],
    [ "external_constructor", "structwpi_1_1detail_1_1external__constructor.html", null ],
    [ "external_constructor< value_t::array >", "structwpi_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
    [ "external_constructor< value_t::boolean >", "structwpi_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
    [ "external_constructor< value_t::number_float >", "structwpi_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
    [ "external_constructor< value_t::number_integer >", "structwpi_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
    [ "external_constructor< value_t::number_unsigned >", "structwpi_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
    [ "external_constructor< value_t::object >", "structwpi_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
    [ "external_constructor< value_t::string >", "structwpi_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
    [ "from_json_fn", "structwpi_1_1detail_1_1from__json__fn.html", "structwpi_1_1detail_1_1from__json__fn" ],
    [ "FutureThen", "structwpi_1_1detail_1_1_future_then.html", null ],
    [ "FutureThen< To, void >", "structwpi_1_1detail_1_1_future_then_3_01_to_00_01void_01_4.html", null ],
    [ "FutureThen< void, From >", "structwpi_1_1detail_1_1_future_then_3_01void_00_01_from_01_4.html", null ],
    [ "FutureThen< void, void >", "structwpi_1_1detail_1_1_future_then_3_01void_00_01void_01_4.html", null ],
    [ "has_from_json", "structwpi_1_1detail_1_1has__from__json.html", null ],
    [ "has_non_default_from_json", "structwpi_1_1detail_1_1has__non__default__from__json.html", null ],
    [ "has_size_and_data", "structwpi_1_1detail_1_1has__size__and__data.html", null ],
    [ "has_size_and_data< T, std::void_t< decltype(std::size(std::declval< T >())), decltype(std::data(std::declval< T >()))> >", "structwpi_1_1detail_1_1has__size__and__data_3_01_t_00_01std_1_1void__t_3_01decltype_07std_1_1siz4b4f562a3d71e72813c0dac0f39a1c47.html", null ],
    [ "has_to_json", "structwpi_1_1detail_1_1has__to__json.html", null ],
    [ "HasPointerLikeTypeTraits", "structwpi_1_1detail_1_1_has_pointer_like_type_traits.html", null ],
    [ "HasPointerLikeTypeTraits< T, decltype((sizeof(PointerLikeTypeTraits< T >)+sizeof(T)), void())>", "structwpi_1_1detail_1_1_has_pointer_like_type_traits_3_01_t_00_01decltype_07_07sizeof_07_pointer671eb09a59b08f00112f7368cac2b1c1.html", null ],
    [ "internal_iterator", "structwpi_1_1detail_1_1internal__iterator.html", "structwpi_1_1detail_1_1internal__iterator" ],
    [ "invalid_iterator", "classwpi_1_1detail_1_1invalid__iterator.html", "classwpi_1_1detail_1_1invalid__iterator" ],
    [ "is_compatible_array_type", "structwpi_1_1detail_1_1is__compatible__array__type.html", null ],
    [ "is_compatible_complete_type", "structwpi_1_1detail_1_1is__compatible__complete__type.html", null ],
    [ "is_compatible_integer_type", "structwpi_1_1detail_1_1is__compatible__integer__type.html", null ],
    [ "is_compatible_integer_type_impl", "structwpi_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
    [ "is_compatible_integer_type_impl< true, RealIntegerType, CompatibleNumberIntegerType >", "structwpi_1_1detail_1_1is__compatible__integer__type__impl_3_01true_00_01_real_integer_type_00_0f4c653c5d50ee25b2348a9a9e62e804d.html", "structwpi_1_1detail_1_1is__compatible__integer__type__impl_3_01true_00_01_real_integer_type_00_0f4c653c5d50ee25b2348a9a9e62e804d" ],
    [ "is_compatible_object_type", "structwpi_1_1detail_1_1is__compatible__object__type.html", null ],
    [ "is_compatible_object_type_impl", "structwpi_1_1detail_1_1is__compatible__object__type__impl.html", null ],
    [ "is_compatible_object_type_impl< true, RealType, CompatibleObjectType >", "structwpi_1_1detail_1_1is__compatible__object__type__impl_3_01true_00_01_real_type_00_01_compatible_object_type_01_4.html", null ],
    [ "is_compatible_type", "structwpi_1_1detail_1_1is__compatible__type.html", null ],
    [ "is_complete", "structwpi_1_1detail_1_1is__complete.html", null ],
    [ "is_complete< T, decltype(sizeof(T))>", "structwpi_1_1detail_1_1is__complete_3_01_t_00_01decltype_07sizeof_07_t_08_08_4.html", null ],
    [ "is_complete_type", "structwpi_1_1detail_1_1is__complete__type.html", null ],
    [ "is_complete_type< T, decltype(void(sizeof(T)))>", "structwpi_1_1detail_1_1is__complete__type_3_01_t_00_01decltype_07void_07sizeof_07_t_08_08_08_4.html", null ],
    [ "is_container", "structwpi_1_1detail_1_1is__container.html", null ],
    [ "is_container_element_type_compatible", "structwpi_1_1detail_1_1is__container__element__type__compatible.html", null ],
    [ "is_container_element_type_compatible< T, E, typename std::enable_if< !std::is_same< typename std::remove_cv< decltype(std::data(std::declval< T >()))>::type, void >::value >::type >", "structwpi_1_1detail_1_1is__container__element__type__compatible_3_01_t_00_01_e_00_01typename_01scdae4824f6922aa996e2434f9c2d2cbe.html", null ],
    [ "is_json", "structwpi_1_1detail_1_1is__json.html", null ],
    [ "is_json< json >", "structwpi_1_1detail_1_1is__json_3_01json_01_4.html", null ],
    [ "is_json_nested_type", "structwpi_1_1detail_1_1is__json__nested__type.html", null ],
    [ "is_span", "structwpi_1_1detail_1_1is__span.html", null ],
    [ "is_span< span< T, S > >", "structwpi_1_1detail_1_1is__span_3_01span_3_01_t_00_01_s_01_4_01_4.html", null ],
    [ "is_std_array", "structwpi_1_1detail_1_1is__std__array.html", null ],
    [ "is_std_array< std::array< T, N > >", "structwpi_1_1detail_1_1is__std__array_3_01std_1_1array_3_01_t_00_01_n_01_4_01_4.html", null ],
    [ "IsPointerLike", "structwpi_1_1detail_1_1_is_pointer_like.html", null ],
    [ "IsPointerLike< T * >", "structwpi_1_1detail_1_1_is_pointer_like_3_01_t_01_5_01_4.html", null ],
    [ "iter_impl", "classwpi_1_1detail_1_1iter__impl.html", "classwpi_1_1detail_1_1iter__impl" ],
    [ "iteration_proxy", "classwpi_1_1detail_1_1iteration__proxy.html", "classwpi_1_1detail_1_1iteration__proxy" ],
    [ "json_ref", "classwpi_1_1detail_1_1json__ref.html", "classwpi_1_1detail_1_1json__ref" ],
    [ "json_reverse_iterator", "classwpi_1_1detail_1_1json__reverse__iterator.html", "classwpi_1_1detail_1_1json__reverse__iterator" ],
    [ "LeadingZerosCounter", "structwpi_1_1detail_1_1_leading_zeros_counter.html", null ],
    [ "other_error", "classwpi_1_1detail_1_1other__error.html", "classwpi_1_1detail_1_1other__error" ],
    [ "out_of_range", "classwpi_1_1detail_1_1out__of__range.html", "classwpi_1_1detail_1_1out__of__range" ],
    [ "parse_error", "classwpi_1_1detail_1_1parse__error.html", "classwpi_1_1detail_1_1parse__error" ],
    [ "PopulationCounter", "structwpi_1_1detail_1_1_population_counter.html", null ],
    [ "PopulationCounter< T, 8 >", "structwpi_1_1detail_1_1_population_counter_3_01_t_00_018_01_4.html", null ],
    [ "primitive_iterator_t", "classwpi_1_1detail_1_1primitive__iterator__t.html", "classwpi_1_1detail_1_1primitive__iterator__t" ],
    [ "priority_tag", "structwpi_1_1detail_1_1priority__tag.html", null ],
    [ "priority_tag< 0 >", "structwpi_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
    [ "PromiseFactoryBase", "classwpi_1_1detail_1_1_promise_factory_base.html", "classwpi_1_1detail_1_1_promise_factory_base" ],
    [ "SafeThreadOwnerBase", "classwpi_1_1detail_1_1_safe_thread_owner_base.html", "classwpi_1_1detail_1_1_safe_thread_owner_base" ],
    [ "SafeThreadProxy", "classwpi_1_1detail_1_1_safe_thread_proxy.html", "classwpi_1_1detail_1_1_safe_thread_proxy" ],
    [ "SafeThreadProxyBase", "classwpi_1_1detail_1_1_safe_thread_proxy_base.html", "classwpi_1_1detail_1_1_safe_thread_proxy_base" ],
    [ "SizerImpl", "unionwpi_1_1detail_1_1_sizer_impl.html", "unionwpi_1_1detail_1_1_sizer_impl" ],
    [ "span_storage", "structwpi_1_1detail_1_1span__storage.html", "structwpi_1_1detail_1_1span__storage" ],
    [ "span_storage< E, dynamic_extent >", "structwpi_1_1detail_1_1span__storage_3_01_e_00_01dynamic__extent_01_4.html", "structwpi_1_1detail_1_1span__storage_3_01_e_00_01dynamic__extent_01_4" ],
    [ "static_const", "structwpi_1_1detail_1_1static__const.html", null ],
    [ "to_json_fn", "structwpi_1_1detail_1_1to__json__fn.html", "structwpi_1_1detail_1_1to__json__fn" ],
    [ "TrailingZerosCounter", "structwpi_1_1detail_1_1_trailing_zeros_counter.html", null ],
    [ "type_error", "classwpi_1_1detail_1_1type__error.html", "classwpi_1_1detail_1_1type__error" ],
    [ "WorkerThreadAsync", "structwpi_1_1detail_1_1_worker_thread_async.html", "structwpi_1_1detail_1_1_worker_thread_async" ],
    [ "WorkerThreadAsync< void >", "structwpi_1_1detail_1_1_worker_thread_async_3_01void_01_4.html", "structwpi_1_1detail_1_1_worker_thread_async_3_01void_01_4" ],
    [ "WorkerThreadRequest", "structwpi_1_1detail_1_1_worker_thread_request.html", "structwpi_1_1detail_1_1_worker_thread_request" ],
    [ "WorkerThreadThread", "classwpi_1_1detail_1_1_worker_thread_thread.html", "classwpi_1_1detail_1_1_worker_thread_thread" ]
];