var namespacehal =
[
    [ "impl", null, [
      [ "SimCallbackRegistryBase", "classhal_1_1impl_1_1_sim_callback_registry_base.html", "classhal_1_1impl_1_1_sim_callback_registry_base" ],
      [ "SimDataValueBase", "classhal_1_1impl_1_1_sim_data_value_base.html", "classhal_1_1impl_1_1_sim_data_value_base" ],
      [ "SimPrefixCallbackRegistry", "classhal_1_1impl_1_1_sim_prefix_callback_registry.html", "classhal_1_1impl_1_1_sim_prefix_callback_registry" ],
      [ "SimUnnamedCallbackRegistry", "classhal_1_1impl_1_1_sim_unnamed_callback_registry.html", "classhal_1_1impl_1_1_sim_unnamed_callback_registry" ]
    ] ],
    [ "sim", null, [
      [ "BufferCallbackStore", "classhal_1_1sim_1_1_buffer_callback_store.html", "classhal_1_1sim_1_1_buffer_callback_store" ],
      [ "CallbackStore", "classhal_1_1sim_1_1_callback_store.html", "classhal_1_1sim_1_1_callback_store" ],
      [ "ConstBufferCallbackStore", "classhal_1_1sim_1_1_const_buffer_callback_store.html", "classhal_1_1sim_1_1_const_buffer_callback_store" ],
      [ "SpiReadAutoReceiveBufferCallbackStore", "classhal_1_1sim_1_1_spi_read_auto_receive_buffer_callback_store.html", "classhal_1_1sim_1_1_spi_read_auto_receive_buffer_callback_store" ]
    ] ],
    [ "AccelerometerData", "classhal_1_1_accelerometer_data.html", "classhal_1_1_accelerometer_data" ],
    [ "AddressableLEDData", "classhal_1_1_addressable_l_e_d_data.html", "classhal_1_1_addressable_l_e_d_data" ],
    [ "AnalogGyroData", "classhal_1_1_analog_gyro_data.html", "classhal_1_1_analog_gyro_data" ],
    [ "AnalogInData", "classhal_1_1_analog_in_data.html", "classhal_1_1_analog_in_data" ],
    [ "AnalogOutData", "classhal_1_1_analog_out_data.html", "classhal_1_1_analog_out_data" ],
    [ "AnalogPort", "structhal_1_1_analog_port.html", "structhal_1_1_analog_port" ],
    [ "AnalogTriggerData", "classhal_1_1_analog_trigger_data.html", "classhal_1_1_analog_trigger_data" ],
    [ "CanData", "classhal_1_1_can_data.html", "classhal_1_1_can_data" ],
    [ "Counter", "structhal_1_1_counter.html", "structhal_1_1_counter" ],
    [ "CTREPCMData", "classhal_1_1_c_t_r_e_p_c_m_data.html", "classhal_1_1_c_t_r_e_p_c_m_data" ],
    [ "DigitalHandleResource", "classhal_1_1_digital_handle_resource.html", "classhal_1_1_digital_handle_resource" ],
    [ "DigitalPort", "structhal_1_1_digital_port.html", "structhal_1_1_digital_port" ],
    [ "DigitalPWMData", "classhal_1_1_digital_p_w_m_data.html", "classhal_1_1_digital_p_w_m_data" ],
    [ "DIOData", "classhal_1_1_d_i_o_data.html", "classhal_1_1_d_i_o_data" ],
    [ "DIOSetProxy", "structhal_1_1_d_i_o_set_proxy.html", "structhal_1_1_d_i_o_set_proxy" ],
    [ "DriverStationData", "classhal_1_1_driver_station_data.html", "classhal_1_1_driver_station_data" ],
    [ "DutyCycle", "structhal_1_1_duty_cycle.html", "structhal_1_1_duty_cycle" ],
    [ "DutyCycleData", "classhal_1_1_duty_cycle_data.html", "classhal_1_1_duty_cycle_data" ],
    [ "Encoder", "classhal_1_1_encoder.html", "classhal_1_1_encoder" ],
    [ "EncoderData", "classhal_1_1_encoder_data.html", "classhal_1_1_encoder_data" ],
    [ "fpga_clock", "classhal_1_1fpga__clock.html", "classhal_1_1fpga__clock" ],
    [ "HandleBase", "classhal_1_1_handle_base.html", "classhal_1_1_handle_base" ],
    [ "I2CData", "classhal_1_1_i2_c_data.html", "classhal_1_1_i2_c_data" ],
    [ "IndexedClassedHandleResource", "classhal_1_1_indexed_classed_handle_resource.html", "classhal_1_1_indexed_classed_handle_resource" ],
    [ "IndexedHandleResource", "classhal_1_1_indexed_handle_resource.html", "classhal_1_1_indexed_handle_resource" ],
    [ "LimitedClassedHandleResource", "classhal_1_1_limited_classed_handle_resource.html", "classhal_1_1_limited_classed_handle_resource" ],
    [ "LimitedHandleResource", "classhal_1_1_limited_handle_resource.html", "classhal_1_1_limited_handle_resource" ],
    [ "PowerDistributionData", "classhal_1_1_power_distribution_data.html", "classhal_1_1_power_distribution_data" ],
    [ "PWMData", "classhal_1_1_p_w_m_data.html", "classhal_1_1_p_w_m_data" ],
    [ "RelayData", "classhal_1_1_relay_data.html", "classhal_1_1_relay_data" ],
    [ "REVPHData", "classhal_1_1_r_e_v_p_h_data.html", "classhal_1_1_r_e_v_p_h_data" ],
    [ "RoboRioData", "classhal_1_1_robo_rio_data.html", "classhal_1_1_robo_rio_data" ],
    [ "SerialHelper", "classhal_1_1_serial_helper.html", "classhal_1_1_serial_helper" ],
    [ "SimCallbackRegistry", "classhal_1_1_sim_callback_registry.html", "classhal_1_1_sim_callback_registry" ],
    [ "SimDataValue", "classhal_1_1_sim_data_value.html", "classhal_1_1_sim_data_value" ],
    [ "SimDeviceData", "classhal_1_1_sim_device_data.html", "classhal_1_1_sim_device_data" ],
    [ "SPIAccelerometerData", "classhal_1_1_s_p_i_accelerometer_data.html", "classhal_1_1_s_p_i_accelerometer_data" ],
    [ "SPIData", "classhal_1_1_s_p_i_data.html", "classhal_1_1_s_p_i_data" ],
    [ "UnlimitedHandleResource", "classhal_1_1_unlimited_handle_resource.html", "classhal_1_1_unlimited_handle_resource" ]
];