var annotated_dup =
[
    [ "CmdAutoDriveStraight", "class_cmd_auto_drive_straight.html", "class_cmd_auto_drive_straight" ],
    [ "CmdAutoTurnAngle", "class_cmd_auto_turn_angle.html", "class_cmd_auto_turn_angle" ],
    [ "CmdBallShooterAtRest", "class_cmd_ball_shooter_at_rest.html", "class_cmd_ball_shooter_at_rest" ],
    [ "CmdBallShooterIntake", "class_cmd_ball_shooter_intake.html", "class_cmd_ball_shooter_intake" ],
    [ "CmdBallShooterShootHigh", "class_cmd_ball_shooter_shoot_high.html", "class_cmd_ball_shooter_shoot_high" ],
    [ "CmdBallShooterShootLow", "class_cmd_ball_shooter_shoot_low.html", "class_cmd_ball_shooter_shoot_low" ],
    [ "CmdDisableSmoothingMode", "class_cmd_disable_smoothing_mode.html", "class_cmd_disable_smoothing_mode" ],
    [ "CmdDisableTurboMode", "class_cmd_disable_turbo_mode.html", "class_cmd_disable_turbo_mode" ],
    [ "CmdDriveArcadeStyle", "class_cmd_drive_arcade_style.html", "class_cmd_drive_arcade_style" ],
    [ "CmdDriveTankStyle", "class_cmd_drive_tank_style.html", "class_cmd_drive_tank_style" ],
    [ "CmdEnableSmoothingMode", "class_cmd_enable_smoothing_mode.html", "class_cmd_enable_smoothing_mode" ],
    [ "CmdEnableTurboMode", "class_cmd_enable_turbo_mode.html", "class_cmd_enable_turbo_mode" ],
    [ "CmdGrpAutoDefault", "class_cmd_grp_auto_default.html", "class_cmd_grp_auto_default" ],
    [ "CmdGrpAutoDefCenter", "class_cmd_grp_auto_def_center.html", "class_cmd_grp_auto_def_center" ],
    [ "CmdGrpAutoDefLeft", "class_cmd_grp_auto_def_left.html", "class_cmd_grp_auto_def_left" ],
    [ "CmdGrpAutoDefRight", "class_cmd_grp_auto_def_right.html", "class_cmd_grp_auto_def_right" ],
    [ "CmdGrpAutoOffCenter", "class_cmd_grp_auto_off_center.html", "class_cmd_grp_auto_off_center" ],
    [ "CmdGrpAutoOffLeft", "class_cmd_grp_auto_off_left.html", "class_cmd_grp_auto_off_left" ],
    [ "CmdGrpAutoOffRight", "class_cmd_grp_auto_off_right.html", "class_cmd_grp_auto_off_right" ],
    [ "CmdResetAHRSYaw", "class_cmd_reset_a_h_r_s_yaw.html", "class_cmd_reset_a_h_r_s_yaw" ],
    [ "CmdToggleDriveDirection", "class_cmd_toggle_drive_direction.html", "class_cmd_toggle_drive_direction" ],
    [ "CmdToggleSmoothingMode", "class_cmd_toggle_smoothing_mode.html", "class_cmd_toggle_smoothing_mode" ],
    [ "CmdWaitSeconds", "class_cmd_wait_seconds.html", "class_cmd_wait_seconds" ],
    [ "CmdZeroAHRSYaw", "class_cmd_zero_a_h_r_s_yaw.html", "class_cmd_zero_a_h_r_s_yaw" ],
    [ "ProjectileMotion", "class_projectile_motion.html", "class_projectile_motion" ],
    [ "Robot", "class_robot.html", "class_robot" ],
    [ "RobotContainer", "class_robot_container.html", "class_robot_container" ],
    [ "RobotTick", "class_robot_tick.html", "class_robot_tick" ],
    [ "SubSysBallShooter", "class_sub_sys_ball_shooter.html", "class_sub_sys_ball_shooter" ],
    [ "SubSysDriveTrain", "class_sub_sys_drive_train.html", "class_sub_sys_drive_train" ],
    [ "TelemetryOutputter", "class_telemetry_outputter.html", "class_telemetry_outputter" ],
    [ "Video", "class_video.html", "class_video" ]
];